export enum CampanhaStatus {
    andamento = 0,
    bloqueada = 1,
    cancelada = 2,
    excluida = 3,
    finalizada = 4,
    pendente = 5,
    importadoComSucesso = 100,
    importadoEmAndamento = 101,
    importadoParcialmente = 102,
    importacaoComFalha = 103,
    importacaoPendente = 104,
    importacaoArquivoInvalido = 105,
    todos = 999,
}
